version: '3.1'

services:

#Database
  db:
    mem_limit: 2048m
    image: mariadb:10.6.4-focal
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    #volumes:
     # - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - wpsite
  # PHPMYADMIN
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wpsite
  # WORDPRESS
  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.2-apache
    restart: always
    ports:
      - 8081:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    volumes:
      ['./wp-content/:/var/www/html/wp-content']
      ##- wordpress:/var/www/html
    networks:
      - wpsite
networks:
  wpsite:      
volumes:
  db_data:
  
  